"""Add column cnt_likes

Revision ID: 2ec5a919622c
Revises: 5a17cfa40a26
Create Date: 2023-08-25 17:35:32.048614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec5a919622c'
down_revision = '5a17cfa40a26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('cnt_likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'cnt_likes')
    # ### end Alembic commands ###
